### ISSUE TITLE
Set HTTP cache-control headers

### ISSUE THREAD

**Issue by ns4plabs** [ipfs/someguy#26]
Currently, someguy does not have a local cache. As a temporary measure we could introduce cache-control HTTP headers and store the results on the reverse proxy.

Is this a reasonable strategy and if so, what is the reasonable time to cache the results? 5 minutes? 1 hour?

**Comment by 2color** [comment]
For reference, since this was already brought up:

https://github.com/protocol/bifrost-infra/issues/2758#issuecomment-1716761794
https://github.com/protocol/bifrost-community/issues/1#issuecomment-1768569187

@aschmahmann Do you have thoughts on whether the cache header configuration belongs in the someguy, boxo (routing server), or the proxy?

I saw that for IPNS we set the [cache header based on the TTL in the IPNS record](https://github.com/ipfs/boxo/blob/main/routing/http/server/server.go#L400-L404). Though for peer and provider records, it seems like this might be something we want in someguy based on the source, e.g. for cid.contact longer than DHT records which are inherently more epheremal.

**Comment by lidel** [comment]
Implementing this in someguy requires delaying sending HTTP headers until we have at least one result. 

Right now, HTTP headers are set before results can be inspected, these are the places where we would add cache-control based on having at least one result:

- without streaming `Accept: application/json` https://github.com/ipfs/boxo/blob/79cb4e2886d72af06f3b102982520a743835c02f/routing/http/server/server.go#L461
- with streaming `Accept: application/x-ndjson`  https://github.com/ipfs/boxo/blob/79cb4e2886d72af06f3b102982520a743835c02f/routing/http/server/server.go#L498

**Comment by hacdias** [comment]
See https://github.com/ipfs/boxo/pull/584
